# Generated by Django 6.0.2 on 2026-03-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_recipeimagemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeImageModel',
            new_name='RecipeImage',
        ),
    ]
