# Generated by Django 6.0.2 on 2026-03-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_alter_recipeimage_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeimage',
            old_name='name',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
